const translations: Record<string, string> = {
  // Layout / Meta
  site_title: "Create Next App",
  site_description: "Generated by create next app",

  // Common
  loading: "Loading...",
  cancel: "Cancel",
  saving: "Saving…",
  save_changes: "Save changes",
  something_went_wrong: "Something went wrong",
  something_went_wrong_try_again: "Something went wrong. Please try again.",
  email_label: "Email",
  password_label: "Password",
  login: "Login",
  sign_in: "Sign in",
  sign_up: "Sign up",
  sign_out: "Sign out",
  approve: "Approve",
  reject: "Reject",
  search: "Search",
  clear: "Clear",
  clear_search: "Clear search",
  free: "Free",
  featured: "Featured",
  profile: "Profile",
  description_label: "Description",
  city_label: "City",
  add: "Add",

  // Auth - Error page
  code_error_prefix: "Code error: ",
  unspecified_error: "An unspecified error occurred.",
  sorry_something_went_wrong: "Sorry, something went wrong.",

  // Auth - Sign Up Success
  account_created: "Account created",
  thank_you_for: "Thank you for ",
  signing_up: "signing up!",
  confirmation_link_sent_to: "We sent a confirmation link to",
  confirmation_link_sent_generic:
    "We sent a confirmation link to your email address.",
  check_inbox_to_activate: "Please check your inbox to activate your account.",
  step_open_email: "Open the email we sent you.",
  step_click_confirm: 'Click the "Confirm your email" button inside.',
  step_redirected: "You'll be redirected to Conecta — ready to explore!",
  go_to_sign_in: "Go to Sign In",
  email_resent_success: "✓ Email resent successfully!",
  didnt_receive_resend: "Didn't receive it? Resend email",

  // Auth - Auth Button
  hey_greeting: "Hey, ",

  // Auth - Forgot Password
  email_sent: "Email sent",
  check_your: "Check Your ",
  email_exclamation: "Email!",
  password_reset_email_sent:
    "If you registered using your email and password, you will receive a password reset link at",
  check_spam_folder: "Don't forget to check your spam folder.",
  back_to_login: "Back to Login",
  password_recovery: "Password recovery",
  reset_your: "Reset Your ",
  password_dot: "Password.",
  reset_password_instructions:
    "Type in your email and we'll send you a link to reset your password.",
  sending: "Sending…",
  send_reset_email: "Send reset email",
  already_have_account: "Already have an account?",

  // Auth - Login
  sign_in_to: "Sign In to ",
  conecta: "Conecta",
  explore_whats_happening: "Explore what's happening around you today.",
  forgot_your_password: "Forgot your password?",
  logging_in: "Logging in...",
  new_here: "New here?",
  create_free_account: "Create a free account",

  // Auth - Sign Up
  sign_up_title: "Sign up",
  create_new_account: "Create a new account",
  full_name_label: "Full Name",
  username_label: "Username",
  username_hint: "Letters, numbers, _ and - only. Min 3 characters.",
  confirm_password_label: "Confirm Password",
  passwords_do_not_match: "Passwords do not match",
  username_min_chars: "Username must be at least 3 characters",
  username_taken: "That username is already taken",
  creating_account: "Creating your account...",

  // Auth - Update Password
  almost_there: "Almost there",
  enter_new_password: "Please enter your new password below.",
  new_password_label: "New password",
  new_password_placeholder: "New password",
  save_new_password: "Save new password",
  hide_password: "Hide password",
  show_password: "Show password",
  strength_weak: "Weak",
  strength_fair: "Fair",
  strength_good: "Good",
  strength_strong: "Strong",

  // Admin
  control_panel: "Control Panel",
  admin: "Admin",
  pending_applications: "Pending Applications",
  pending_events: "Pending Events",
  approved_events: "Approved Events",
  total_users: "Total Users",
  applications_tab: "Applications",
  events_tab: "Events",
  featured_tab: "Featured",
  users_tab: "Users",
  no_pending_applications: "No pending applications",
  no_pending_events: "No pending events",
  no_approved_events: "No approved events",
  no_users_found: "No users found",
  contact_prefix: "Contact: ",
  rejection_reason_placeholder: "Rejection reason (optional)",
  rejection_note_placeholder: "Rejection note (optional)",
  unfeature: "Unfeature",
  feature: "Feature",
  search_users_placeholder: "Search by name or username…",
  full_name_field: "Full name",
  username_field: "Username",
  bio_field: "Bio",
  city_field: "City",
  user_type_field: "User type",
  application_status_field: "Application status",
  user_option: "User",
  organizer_option: "Organizer",
  admin_option: "Admin",
  pending_option: "Pending",
  approved_option: "Approved",
  rejected_option: "Rejected",
  organizer_info: "Organizer info",
  organizer_name_field: "Organizer name",
  contact_info_field: "Contact info",

  // Events - Create
  cover: "Cover",
  add_photo: "Add photo",
  image_upload_hint: "First image is the cover · Up to 8 images",
  event_submitted: "Event Submitted!",
  event_pending_review:
    "Your event is pending review and will appear publicly once approved.",
  go_to_dashboard: "Go to Dashboard",
  create_another: "Create Another",
  create_event: "Create Event",
  event_review_notice: "Your event will be reviewed before it goes live.",
  event_details: "Event Details",
  title_label: "Title",
  type_section: "Type",
  category_section: "Category",
  date_and_time: "Date & Time",
  start_date_required: "Start date *",
  start_time_required: "Start time *",
  end_date_label: "End date",
  end_time_label: "End time",
  images_section: "Images",
  at_least_one_image: "At least one image is required.",
  additional_info: "Additional Info",
  price_label: "Price",
  capacity_label: "Capacity",
  contact_registration_link: "Contact / Registration Link",
  submitting: "Submitting…",
  submit_for_review: "Submit for Review",

  // Events - Detail
  back_to_events: "Back to Events",
  copied: "Copied",
  share: "Share",
  organized_by: "Organized by",
  date_label: "Date",
  time_label: "Time",
  location_label: "Location",
  spots_suffix: "spots",
  get_in_touch: "Get in Touch",
  this_event_is_featured: "✦ This event is featured",

  // Events - List / Client
  search_events_placeholder: "Search events…",
  featured_events: "Featured Events",
  results: "Results",
  all_events: "All Events",
  no_events_found: "No events found.",

  // Events - Carousel
  trending_this_week: "Trending This Week",
  view_all_events: "View All Events",
  by_prefix: "By ",
  details: "Details",

  // Header
  header_login: "Login",
  header_sign_up: "Sign up",
  admin_dashboard: "Admin Dashboard",

  // Footer
  footer_description:
    "Connecting people through experiences. The #1 event discovery platform in Honduras.",
  footer_copyright: "© 2026 ConectaHonduras Inc.",
  discover: "Discover",
  featured_events_link: "Featured Events",
  this_weekend: "This Weekend",
  trending: "Trending",
  categories: "Categories",
  organizers: "Organizers",
  post_an_event: "Post an Event",
  promote_brand: "Promote Brand",
  pricing: "Pricing",
  success_stories: "Success Stories",
  company: "Company",
  about_us: "About Us",
  careers: "Careers",
  contact: "Contact",
  legal: "Legal",

  // Home - Trusted By Organizers
  trusted_by_organizers: "Trusted by Organizers",

  // Home - Search Interface
  location: "Location",
  looking_for: "Looking For",

  // Profile
  my_account: "My Account",
  edit: "Edit",
  my: "My",
  edit_profile: "Edit Profile",
  profile_updated: "Profile updated successfully!",
  cannot_be_changed: "· cannot be changed",
  optional_suffix: "· optional",
  no_bio_yet: "No bio yet.",
  photos: "Photos",

  // Profile - Apply Dialog
  reapply_as_organizer: "Re-apply as Organizer",
  apply_to_become_organizer: "Apply to Become an Organizer",
  review_timeline: "Our team reviews applications within 3–5 business days.",
  application_submitted: "Application Submitted!",
  reach_out_when_reviewed: "We'll reach out once it's been reviewed.",
  organizer_brand_name: "Organizer / Brand Name",
  contact_information: "Contact Information",
  contact_reach_hint: "How the team or attendees can reach you.",
  agree_to_conecta: "I agree to Conecta's ",
  organizer_terms: "Organizer Terms",
  and_text: " and ",
  community_guidelines: "Community Guidelines",
  approval_not_guaranteed: ". I understand approval is not guaranteed.",
  submit_application: "Submit Application",
  submission_failed: "Submission failed.",

  // Profile - Avatar
  change_photo: "Change photo",
  change_avatar: "Change avatar",

  // Profile - Organizer Section
  organizer_profile: "Organizer Profile",
  organizer_name_label: "Organizer Name",
  save_organizer_info: "Save Organizer Info",
  verified_organizer: "Verified Organizer",
  application_under_review: "Application Under Review",
  notify_when_reviewed: "We'll notify you once it's been reviewed.",
  application_not_approved: "Application Not Approved",
  reason_prefix: "Reason: ",
  reapply: "Re-apply",
  become_event_organizer: "Become an Event Organizer",
  create_manage_events: "Create and manage events on Conecta.",
  apply: "Apply",

  // Profile - Photos Grid
  no_photos_yet: "No photos yet.",

  // Profile - Constants
  under_review: "Under Review",
  status_pending_description:
    "We'll email you once your application has been reviewed.",
  not_approved: "Not Approved",
  status_rejected_description:
    "You can submit a new application with updated information.",
  status_approved_description:
    "You have full access to create and manage events.",

  // Events Create Page (server)
  application_under_review_title: "Application Under Review",
  organizer_app_under_review:
    "Your organizer application is being reviewed. You'll be able to create events once it's approved. This usually takes 1–2 business days.",
  back_to_events_arrow: "← Back to events",
  organizers_only: "Organizers Only",
  organizers_only_description:
    "Only verified organizers can publish events. Apply to become an organizer from your profile page — it's free and takes just a few minutes.",
  apply_as_organizer: "Apply as Organizer",
  browse_events: "Browse Events",

  // Env Var Warning
  supabase_env_required: "Supabase environment variables required",

  // Location Field
  search_location_placeholder: "Search for a location...",
  no_results_found: "No results found.",

  // Common - Error
  an_error_occurred: "An error occurred",

  // Auth - Sign Up Form (validation)
  // (passwords_do_not_match, username_min_chars, username_taken already exist above)

  // Events - Create Form (validation)
  title_min_chars: "Title must be at least 3 characters",
  title_max_chars: "Max 120 characters",
  description_min_chars: "Description must be at least 10 characters",
  description_max_chars: "Max 2000 characters",
  city_required: "City is required",
  please_pick_category: "Please pick a category",
  please_select_type: "Please select a type",
  start_date_is_required: "Start date is required",
  start_time_is_required: "Start time is required",
  must_be_valid_url: "Must be a valid URL",
  must_be_valid_positive_number: "Must be a valid positive number",
  must_be_whole_number_gt_zero: "Must be a whole number greater than 0",
  end_must_be_after_start: "End date/time must be after start",

  // Events - Create Form (tooltips & placeholders)
  price_display_only: "Display only — no payments are processed",
  capacity_display_only: "Display only — no internal seat counting",
  external_link_tooltip:
    "WhatsApp, Instagram, Eventbrite — wherever people can contact you",
  unlimited: "Unlimited",

  // Events - List
  search_placeholder_concerts: "Concerts, art, tech...",
};

export function translate(key: string): string {
  return translations[key] ?? key;
}
